### ISSUE TITLE
Failed update

### ISSUE THREAD

**Issue by dromian** [TeraProxy/Cosplayer#10]
ERROR: Unable to auto-update module Cosplayer-master:
Failed to update the following module files:
 - presets.json
 - StatusCodeError: 404 - {"type":"Buffer","data":[52,48,52,58,32,78,111,116,32,70,111,117,110,100,10]}
Please go to https://github.com/TeraProxy/Cosplayer/issues and follow the given instructions or ask for help.
Alternatively, join https://discord.gg/maqBmJV and ask in the #help channel. pls help

**Comment by TeraProxy** [comment]
Fixed. Sorry for that. Please restart proxy.

**Comment by dromian** [comment]
Ty :D
