### ISSUE TITLE
Lancer little bug

### ISSUE THREAD

**Issue by Hachiman2810** [TeraProxy/Cosplayer#16]
When you select any costume or weapon skin and you exit from dressing room, you got your original weapon skin and you need to use any skill to get the cosplay.

![animated gif-source](https://user-images.githubusercontent.com/40275707/44500065-6199e100-a64c-11e8-9764-d391182147ad.gif)

![animated gif-source 1](https://user-images.githubusercontent.com/40275707/44500224-2d72f000-a64d-11e8-82e1-b2ad201f7b85.gif)

**Comment by TeraProxy** [comment]
Unfortunately this seems to be a client issue. Can't really fix this.
All new designs are applied directly to the client with the same packet so the weapon is already changed but the client only notices it after you use a skill. The only one who can fix this properly is BHS.
