### ISSUE TITLE
台服(TW)目前 74.3 不支持 S_ABNORMALITY_BEGIN.3 需要使用 S_ABNORMALITY_BEGIN.2

### ISSUE THREAD

**Issue by zc149352394** [TeraProxy/Cosplayer#17]
台服(TW)目前 74.3 不支持 S_ABNORMALITY_BEGIN.3 需要使用 S_ABNORMALITY_BEGIN.2

**Comment by TeraProxy** [comment]
Looks like the Taiwanese server is still running on patch 74.3. Other versions (> 75) need a newer definition file. I'll try to fix it.

**Comment by TeraProxy** [comment]
The issue should be fixed now, I added support for older patch versions.
