### ISSUE TITLE
game must lag at the very moment when dragon head buff disappeared

### ISSUE THREAD

**Issue by lsyyktv** [TeraProxy/Cosplayer#18]
game must lag at the very moment when dragon head buff disappeared if I'm using any skill

dragon head=![2](https://user-images.githubusercontent.com/39065858/51235565-cdd60200-19aa-11e9-8923-d161c6b8e9cf.jpg)

**Comment by TeraProxy** [comment]
That's nothing I can fix unfortunately. When the Marrow Brooch (Dragon Head) buff disappears, Cosplayer has to reapply your outfit because it gets reverted to original after buff is gone.
Changing your character's outfit again can give you an FPS drop on slower machines.
