### ISSUE TITLE
Cosplayer doesn't save costumes after relog

### ISSUE THREAD

**Issue by dimitri1337** [TeraProxy/Cosplayer#2]
This has happening for days now, whenever I choose costume, and I crash or relog from the game, the costumes are not saved on your character after you log in again. It didn't happen before till now. Help?

**Comment by dimitri1337** [comment]
Great, no anwser, thank you.

**Comment by piecemealcranky** [comment]
Yeah it doesn't save for me either. There should be a file called presets.json that holds this information.

**Comment by NGSalem** [comment]
I can also confirm the presets.json file no longer updates upon closing proxy and restarting. However manually inputting your costume ids into the file yourself and saving will workaround this issue.

You should be able to find any of the IDs via http://teradatabase.net/us/search/

**Comment by TeraProxy** [comment]
Hi, sorry for the late answer. Pretty busy time for me atm.
I have fixed the bug but still need to update the module for the current patch.
Once I got it working again, I will release it with the bug fix (it was really stupid).
Thanks for letting me know!
