### ISSUE TITLE
Flying mount unusable when cosplaying a mount

### ISSUE THREAD

**Issue by Owyn** [TeraProxy/Cosplayer#20]
Flying mount unusable when cosplaying a mount - can't fly on it

**Comment by TeraProxy** [comment]
Did you try to use a ground mount for flying? That will probably not work.
Changing your mount with a flying mount will let you fly properly (at least with all the ones I tested).

Might also be related to an out of date database. You play on RU, right? I'll update the database now. Maybe it will be fixed afterwards.

**Comment by Owyn** [comment]
Yea, I cosplayed a non-flying mount

**Comment by TeraProxy** [comment]
Ah, I see. It's kinda unfortunate but I can't change that since everything is basically "as-is" from the datacenter. Just try to use only flying mounts when you actually want to fly =)
I'm going to add that to the readme as well. Thank you!

**Comment by Owyn** [comment]
I mean, I want non-flying mount to replace my non-flying mount that's all... but also I need my flying mount to fly, so is it possible to keep my flying one original and not replaced maybe?
