### ISSUE TITLE
Delete the 'region' property from manifest.json

### ISSUE THREAD

**Issue by valkyr1e-tera** [TeraProxy/Cosplayer#21]
With Next²Gen Proxy, proxy no longer distinguishes region.
Therefore, proxy does not compare the file of the item having the region property, so auto-update will not be done even if the file is updated.

**Comment by valkyr1e-tera** [comment]
@TeraProxy ping

**Comment by TeraProxy** [comment]
Caali whyyyyyy q_q

**Comment by TeraProxy** [comment]
For now I'll simply do as you suggested and remove the region property from the manifest of my mods.

I'm gonna try to update them later this month with the Next³Gen Proxy's ability to query from the game's datacenter directly which will improve some of my mods by a lot. Let's hope it all works out fine :)
