### ISSUE TITLE
Don't save clothes after dressing room

### ISSUE THREAD

**Issue by TarTarForas** [TeraProxy/Cosplayer#22]
I have many clothes in dressing room, so mod seems as actually work, but after getting out dressing room clothes don't save.

**Comment by lofuy** [comment]
i have the same problem but i found a method to palliate but the costume reset after each tp 
i just use the command "cosplay enchant 25" and my skin go like i wanted in dressing room

**Comment by TeraProxy** [comment]
I just tested it again and all works fine.... really strange.

Are you sure you are using right-click on the items and not left-click? (see readme)

**Comment by Pochatok89** [comment]
Good day!
After updating the ToolBox, the mod does not save the skin. How to fix?
