### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Momokta** [TeraProxy/Cosplayer#3]
when im in dressing room and rightclick on the costumes it disconnects me and give me errors

**Comment by Denver3D** [comment]
Error https://i.imgur.com/HdeLg8E.png

**Comment by TeraProxy** [comment]
@Denver3D update your tera-data
@Momokta What's the error? Did you copy the node_modules stuff into the right folder?

**Comment by Denver3D** [comment]
@TeraProxy Already updated but still this error didn't changed 

https://i.imgur.com/Q5MNC98.png

Maybe cause I'm on tera EU ? and the EU miss some opcode than the NA ?

**Comment by RoyL21** [comment]
Hey I need help, I'm getting this error also... 
https://imgur.com/a/Kd8Ld
%1 is not a valid win32 application..
Steps done:
-Updated tera-data
-Move file to teraproxy/node-modules
-Research
, please help me I've tried everything even asking at the discord channel

**Comment by TeraProxy** [comment]
@Denver3D I don't see the most important part of the error message but that might be true. I only tested on NA and included the necessary opcodes in tera-data. EU might be missing some.

@RoyL21 Might be because you are on different OS than me. What you can try is installing win-mouse yourself by doing a "npm install win-mouse" in the windows command prompt or powershell.

**Comment by Denver3D** [comment]
@TeraProxy Is there anyway to get more opcode on the EU ? :'(

**Comment by gievepix** [comment]
Doesn't work on RU too (protocol version 324672).
Seems like there is no needed opcodes in this protocol version or something like that.
![image](https://user-images.githubusercontent.com/35334017/35072649-48766f58-fc07-11e7-873b-c6d5fa4eaba2.png)

**Comment by TeraProxy** [comment]
Updated installation instructions and tested them on a clean Windows 7 64-bit installation. Seems like most issues come from having an older or non 64-bit Node.JS version, so I added version checks to Cosplayer.

Advanced users: People who want to use it for 32-bit systems or older Node.JS versions (for whatever reasons) need to build win-mouse themselves.

I'm sorry, guys, but I can only support NA as that's the region I'm playing on. I lack the time to map opcodes for other regions. If you need opcodes, try to map them yourself by following this guide: https://github.com/beng-mods/opcodes-4-dummies
