### ISSUE TITLE
The fitting room is empty

### ISSUE THREAD

**Issue by war100ck** [TeraProxy/Cosplayer#30]
After the last update of the module, not a single object is visible in the fitting room.
![TERA_ScreenShot_20190824_234733_800](https://user-images.githubusercontent.com/921594/63646430-304e6800-c71b-11e9-82ee-43294f02f55d.jpg)
Reinstalling the module did not solve the problem.

**Comment by fangch2004** [comment]
same problem

**Comment by bananzi** [comment]
same problem, too

**Comment by bananei** [comment]
having the same problem on NA
tried reinstalling, removing all gpk mods, with and without pinkie dc mod and still empty dress room

**Comment by Teramystic** [comment]
having same problem for **EU**

**Comment by TeraProxy** [comment]
Fixed in the latest update. The developers changed the Contract Type for the Dressing Room after patch 85.
