### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gh346gfh** [TeraProxy/Cosplayer#4]
says my version of nodes.js is old when its version 9.8.0

![image](https://user-images.githubusercontent.com/37388925/37438981-fa191040-27b2-11e8-9d72-a27710625354.png)

**Comment by TeraProxy** [comment]
I updated to 9.8.0 as well and cannot reproduce the problem.

Please update Cosplayer once more (just updated it) and try to run it. It should now tell you which version of Node.JS is running on your system. Let me know the output.
