### ISSUE TITLE
Weapon Skin disappears after zerk unleash

### ISSUE THREAD

**Issue by Combataccelerator** [TeraProxy/Cosplayer#8]
if you use the zerk awakening the weapon skin disappears after using it .

**Comment by TeraProxy** [comment]
Thanks for letting me know. Looks like I need to dig into abnormals once again...

**Comment by TeraProxy** [comment]
@Combataccelerator I'll push a potential fix with the next update. Unfortunately I don't have an awakened Berserker to test with. Let me clarify: The weapon skin resets to the original one after the Unleashed effect is over. During Unleashed (when you have 2 axes basically) the weapon skin is still changed?

**Comment by Combataccelerator** [comment]
hey sorry for the late answer i wasnt be able to get to my computer the last few days due to work and stuff . You got a premade weapon skin for the unleash mode of the berserker so you dont see any weapon skin while in unleash , but after it the weapon skin resets to the original one yes . Im gonna try the update now and tell you then if it works .

**Comment by TeraProxy** [comment]
Thank you @Hachiman2810 . I will look into this again.

**Comment by TeraProxy** [comment]
Update pushed. Hope this one works now.

**Comment by Hachiman2810** [comment]
It worked. ^^
